[workspace]
members = [
    "era-compiler-common",
    "era-compiler-downloader",
]
resolver = "2"

[workspace.package]
authors = [
    "Anton Baliasnikov <aba@test.com>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
version = "1.5.0"
