[package]
name = "compiler-common"
version = "1.3.3"
authors = [
    "Oleksandr Zarudnyi <a.zarudnyy@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "The Matter Labs compilers common constants"

[lib]
doctest = false
