[package]
name = "compiler-common"
version = "1.3.1"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "The zkEVM compilers common constants"

[lib]
doctest = false
